syntax = "proto3";

package matcher;

import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";

option go_package = "matcher_v1;matcherv1";

enum Sex {
  SEX_UNSPECIFIED = 0;
  SEX_MALE = 1;
  SEX_FEMALE = 2;
}

enum UserType {
  USER_TYPE_UNSPECIFIED = 0;
  USER_TYPE_STUDENT = 1;
  USER_TYPE_WORKER = 2;
  USER_TYPE_TOURIST = 3;
}

message Point {
  double lat = 1;
  double lon = 2;
}

message Parameters {
  string name = 1;
  string surname = 2;
  Point geo = 3;
  repeated string photos = 4;
  int32 budget = 5;
  int32 room_count = 6;
  int32 roommates_count = 7;
  int32 month = 8;
  int32 age = 9;
  bool smoking = 10;
  bool alko = 11;
  bool pet = 12;
  Sex sex = 13;
  UserType user_type = 14;
  string description = 15;
}

message Form {
  string id = 1;
  string user_id = 2;
  Parameters parameters = 3;
  bool active = 4;
  google.protobuf.Timestamp created_at = 5;
  google.protobuf.Timestamp updated_at = 6;
}

message GroupRequest {
  string id = 1;
  string group_id = 2;
  string user_id = 3;
  google.protobuf.Timestamp created_at = 4;
}

message Group {
  string id = 1;
  string owner_id = 2;
  Parameters parameters = 3;
  int32 max_users = 4;
  google.protobuf.Timestamp created_at = 5;
  google.protobuf.Timestamp updated_at = 6;
}

message GroupWithScore {
  Group group = 1;
  float score = 2; 
}

// Form Service
service FormService {
  rpc CreateForm(CreateFormRequest) returns (google.protobuf.Empty);
  rpc GetFormByUser(GetFormByUserRequest) returns (Form);
  rpc UpdateForm(UpdateFormRequest) returns (google.protobuf.Empty);
  rpc DeleteForm(DeleteFormRequest) returns (google.protobuf.Empty);
}

message CreateFormRequest {
  string user_id = 1;
  Parameters parameters = 2;
}

message GetFormByUserRequest {
  string user_id = 1;
}

message GetGroupByUserRequest {
  string user_id = 1;
}
message UpdateFormRequest {
  string user_id = 1;
  Parameters parameters = 2;
}

message DeleteFormRequest {
  string user_id = 1;
}

// GroupQuery Service
service GroupQueryService {
  rpc GetGroup(GetGroupRequest) returns (Group);
  rpc GetGroupByUser(GetGroupByUserRequest) returns (Group);
  rpc DeleteGroup(DeleteGroupRequest) returns (google.protobuf.Empty);
  rpc ListGroupMembers(ListGroupMembersRequest) returns (ListGroupMembersResponse);
}

message GetGroupRequest {
  string group_id = 1;
}

message DeleteGroupRequest {
  string owner_id = 1;
}

message ListGroupMembersRequest {
  string group_id = 1;
}

message ListGroupMembersResponse {
  repeated Form members = 1;
}

// FindGroup Service
service FindGroupService {
  rpc FindGroups(FindGroupsRequest) returns (FindGroupsResponse);
}

message FindGroupsRequest {
  string user_id = 1;
}

message FindGroupsResponse {
  repeated GroupWithScore groups = 1;
}

// Group Service
service GroupService {
  rpc GetReqeusts(GetReqeustsRequest) returns (GetReqeustsResponse);
  rpc SendJoinRequest(SendJoinRequestRequest) returns (SendJoinRequestResponse);
  rpc AcceptJoinRequest(AcceptJoinRequestRequest) returns (google.protobuf.Empty);
  rpc RejectJoinRequest(RejectJoinRequestRequest) returns (google.protobuf.Empty);
}

message GetReqeustsRequest {
  string group_id = 1;
}

message GetReqeustsResponse {
  repeated GroupRequest requests = 1;
}

message SendJoinRequestRequest {
  string user_id = 1;
  string group_id = 2;
}

message SendJoinRequestResponse {
  string request_id = 1; // UUID создаваемого запроса на вступление
}

message AcceptJoinRequestRequest {
  string owner_id = 1;
  string request_id = 2;
}

message RejectJoinRequestRequest {
  string owner_id = 1;
  string request_id = 2;
}
