syntax = "proto3";

package chat;

import "google/protobuf/timestamp.proto";

option go_package = "chat.v1;chatv1";

service ChatService {
  rpc SendMessage(stream SendMessageRequest) returns (stream SendMessageResponse);
  rpc GetChatsByUser(GetChatByUserRequest) returns (GetChatByUserResponse);
  rpc SetLastReadMessage(SetLastReadMessageRequest) returns (SetLastReadMessageResponse);
}

message SendMessageRequest {
  string chat_id = 1;
  string user_id = 2;
  string text = 3;
}

message SendMessageResponse {
  string chat_id = 1;
  User user = 2;
  string text = 3;
  google.protobuf.Timestamp created_at = 4;
}

message GetChatByUserRequest {
  string user_id = 1;
}

message GetChatByUserResponse {
  repeated Chat chat = 1;
}

message SetLastReadMessageRequest {
  string chat_id = 1;
  string user_id = 2;
  google.protobuf.Timestamp last_read_message_at = 3;
}

message SetLastReadMessageResponse {
}

message User {
  string id = 1;
  string name = 2;
  string avatar = 3;
}

message Chat {
  string id = 1;
  string name = 2;
  string avatar = 3;
  repeated User members = 4;
}
